<a href="https://colab.research.google.com/github/dduniverse/datacampus/blob/main/DA/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello World')

Hello World


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np

In [ ]:
np_arr=np.arange(1000000)
list_arr=list(range(1000000))

In [ ]:
%time for _ in range(10):my_arr=np_arr*2
%time for _ in range(10):my_arr=[x*2 for x in list_arr]

CPU times: user 17.1 ms, sys: 5.17 ms, total: 22.3 ms
Wall time: 26.3 ms
CPU times: user 828 ms, sys: 191 ms, total: 1.02 s
Wall time: 1.02 s


In [ ]:
print(type(np.array(1)))
print(type(np.array(0.1)))
print(type(np.array('str')))
print(type(np.array(True)))
print(type(np.array(['list'])))
print(type(np.array(('typle'))))
print(type(np.array(({'key':'value'}))))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
rand_data=np.random.randn(2,3)
print(rand_data)
print(rand_data*10)
print(rand_data+rand_data)

[[ 1.11963689 -1.61769491  0.96656838]
 [-1.34691874 -0.90713539  0.04624092]]
[[ 11.19636889 -16.17694906   9.66568377]
 [-13.46918741  -9.07135395   0.46240916]]
[[ 2.23927378 -3.23538981  1.93313675]
 [-2.69383748 -1.81427079  0.09248183]]


In [ ]:
print(type(rand_data))
print(rand_data.shape)
print(rand_data.ndim)
print(rand_data.dtype)

<class 'numpy.ndarray'>
(2, 3)
2
float64


In [ ]:
list_arr=[[1,2,3],[4,5,6]]
print(list_arr)
print(type(list_arr))

np_arr=np.array([[1,2,3],[4,5,6]])
print(np_arr)
print(type(np_arr))

print(np_arr.ndim)
print(np_arr.shape)
print(np_arr.shape[0])
print(np_arr.shape[1])
print(np_arr.dtype)

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
2
3
int64


In [ ]:
list_arr=[[1.0,2.0,3.0],[4,5,6]]
np_arr=np.array(list_arr)
print(np_arr.dtype) # 실수형, 정수형이 같이있으면 list의 dype은실수형

float64


In [ ]:
my_data=np.array([1,2,3])
print(my_data, my_data.shape)

my_data=np.arange(3,0,-1)
print(my_data, my_data.shape)

my_data=np.ones(3)
print(my_data, my_data.shape)

my_data=np.ones_like([5,4,3,2,1,0])
print(my_data, my_data.shape)

[1 2 3] (3,)
[3 2 1] (3,)
[1. 1. 1.] (3,)
[1 1 1 1 1 1] (6,)


In [ ]:
my_data=np.zeros(3)
print(my_data,my_data.shape)

my_data=np.zeros_like([5,4,3,2,1,0])
print(my_data, my_data.shape)

my_data=np.full((4,2,4),True)
print(my_data, my_data.shape, my_data.dtype)

my_data=np.full_like(list_arr, True) # list_arr이 float type이었기 때문에 True는 1로 채워짐
print(my_data, my_data.shape, my_data.dtype)

[0. 0. 0.] (3,)
[0 0 0 0 0 0] (6,)
[[[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]]] (4, 2, 4) bool
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


In [ ]:
int_arr=np.array([1,2,3,4,5])
print(int_arr,int_arr.dtype)

float_arr=int_arr.astype(np.float64)
print(float_arr,float_arr.dtype)

string_arr=np.array(['+1.25','-9.7','43'],dtype=np.string_)
print(string_arr,string_arr.dtype)

string_to_float_arr=string_arr.astype(float)
print(string_to_float_arr,string_to_float_arr.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[b'+1.25' b'-9.7' b'43'] |S5
[ 1.25 -9.7  43.  ] float64


In [ ]:
full_data=np.full((4,5),2)
print(full_data)

print(full_data+full_data)
print(full_data-full_data)
print(full_data*full_data)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [ ]:
print(full_data*1.5)
print(full_data/2)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np_arr=np.array([[1,3,5],[2,4,6]])
np_arr2=np.array([[-2,3,-2],[4,8,-12]])

print(np_arr < np_arr2) # 각 자리의 값끼리 T/F 비교
print(np_arr > np_arr2)
print(np_arr <= np.array([[4],[4]]))

[[False False False]
 [ True  True False]]
[[ True False  True]
 [False False  True]]
[[ True  True False]
 [ True  True False]]


In [ ]:
arange_data=np.arange(10)
list_data=list(range(10))
print(arange_data)
print(list_data)

print(arange_data[3])
print(list_data[3])
print(arange_data[2:7]) # 슬라이싱
print(list_data[2:7])

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
3
3
[2 3 4 5 6]
[2, 3, 4, 5, 6]


In [ ]:
arange_array=np.array([np.arange(0,4),
                       np.arange(4,8),
                       np.arange(8,12),
                       np.arange(12,16)])
print(arange_array)

# 0행 1열
print(arange_array[0][1])
print(arange_array[0,1])

# 0행 전체
print(arange_array[0])
print(arange_array[0][:])
print(arange_array[0, ])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
1
1
[0 1 2 3]
[0 1 2 3]
[0 1 2 3]


In [ ]:
print(arange_array[:3,1:])
print(arange_array[:,3])
print(arange_array[:,3:4])
print(arange_array[1,:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[ 3  7 11 15]
[[ 3]
 [ 7]
 [11]
 [15]]
[4 5 6]


In [ ]:
for x in range(2,7):
  list_data[x]=-1
print(list_data, type(list_data))

# ndarray 객체는 for문 없이 값 변경 가능
arange_data[2:7]=-1
print(arange_data, arange_data.dtype)

arange_array[1,:2]=-1
print(arange_array)

[0, 1, -1, -1, -1, -1, -1, 7, 8, 9] <class 'list'>
[ 0  1 -1 -1 -1 -1 -1  7  8  9] int64
[[ 0  1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arange_data=np.arange(10)
list_data=list(range(10))

arange2_data=arange_data[3:6]
print(arange2_data)
list2_data=list_data[3:6]
print(list2_data)

arange2_data[1]=9
list2_data[1]=9

print(arange_data)
print(list_data)
print(arange2_data)
print(list2_data)

[3 4 5]
[3, 4, 5]
[0 1 2 3 9 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3 9 5]
[3, 9, 5]


In [ ]:
n_data=np.array([0.25,0.5,0.75,1.0,1.25])
m_data=[n_data,n_data,n_data]
print(m_data)

n_data[0]=-1
print(m_data) # n값을 바꿨기 때문에 m에도 영향.

[array([0.25, 0.5 , 0.75, 1.  , 1.25]), array([0.25, 0.5 , 0.75, 1.  , 1.25]), array([0.25, 0.5 , 0.75, 1.  , 1.25])]
[array([-1.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([-1.  ,  0.5 ,  0.75,  1.  ,  1.25]), array([-1.  ,  0.5 ,  0.75,  1.  ,  1.25])]


In [ ]:
one_data=np.ones(15).reshape(3,5)
arange_data=np.arange(15).reshape(one_data.shape)
print(arange_data.shape)

print(np.reshape(arange_data,(5,3)))
print(arange_data.reshape((5,3)))
print(arange_data.shape)

(3, 5)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(3, 5)


In [ ]:
arange_data=arange_data.reshape((5,3))
print(arange_data)
print(arange_data.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)


In [ ]:
arange_data=np.arange(24).reshape((2,4,-1))
print(arange_data.shape)

arange_Data=np.arange(24).reshape((2,-1,3))
print(arange_Data.shape)

(2, 4, 3)
(2, 4, 3)


In [ ]:
arange_data=np.arange(15).reshape(3,5)
print(arange_Data,arange_data.shape)

arange_data2=np.ravel(arange_data)
print(arange_data2,arange_data2.shape)

arange_data2[0]=-1
print(arange_data,arange_data.shape)
print(arange_data2,arange_data2.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] (3, 5)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
[-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)


In [ ]:
data1=np.arange(0,15).reshape(3,5)
data2=np.arange(15,30).reshape(3,5)
print(data1)
print(data2)

print(np.concatenate([data1,data2],0))
print(np.vstack((data1,data2)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
print(np.concatenate([data1,data2],1))
print(np.hstack((data1,data2)))

[[ 0  1  2  3  4 15 16 17 18 19]
 [ 5  6  7  8  9 20 21 22 23 24]
 [10 11 12 13 14 25 26 27 28 29]]
[[ 0  1  2  3  4 15 16 17 18 19]
 [ 5  6  7  8  9 20 21 22 23 24]
 [10 11 12 13 14 25 26 27 28 29]]


In [ ]:
arange_data=np.arange(30).reshape(6,5)

print(arange_data)
print(np.split(arange_data,3))
print(np.split(arange_data,[2,3]))
print(np.split(arange_data,[2,5]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29]])]


In [ ]:
print(np.vsplit(arange_data,3))
print(np.vsplit(arange_data,[2,3]))
print(np.vsplit(arange_data,[2,5]))

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29]])]


In [ ]:
print(np.split(arange_data,5,1))
print(np.hsplit(arange_data,5))
print(np.hsplit(arange_data,[1,2])) 
print(np.hsplit(arange_data,[1,3]))

[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29]])]
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29]])]
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]]), array([[ 2,  3,  4],
       [ 7,  8, 

In [ ]:
arange_data=np.arange(5)
print(arange_data)

print(np.repeat(arange_data,5))
print(np.repeat(arange_data,[1,1,3,2,1]))
print(np.repeat(arange_data,[0,0,3,0,0]))

[0 1 2 3 4]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]
[0 1 2 2 2 3 3 4]
[2 2 2]


In [ ]:
print(np.tile(arange_data,2))
print(np.tile(arange_data,(1,3)))
print(np.tile(arange_data,(3,1)))

[0 1 2 3 4 0 1 2 3 4]
[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
arange_data=np.arange(15).reshape((3,5))
print(np.repeat(arange_data,2))

print(np.repeat(arange_data,2,0))
print(np.repeat(arange_data,2,1))

print(np.tile(arange_data,2))
print(np.tile(arange_data,(1,3)))
print(np.tile(arange_data,(3,2)))

[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11
 12 12 13 13 14 14]
[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [10 11 12 13 14]]
[[ 0  0  1  1  2  2  3  3  4  4]
 [ 5  5  6  6  7  7  8  8  9  9]
 [10 10 11 11 12 12 13 13 14 14]]
[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]]
[[ 0  1  2  3  4  0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14 10 11 12 13 14]]
[[ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]
 [ 0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14]]


In [ ]:
import numpy as np
np.set_printoptions(linewidth=np.inf)

In [ ]:
name_arr=np.array(['지빈','명환','연지','하람','연지','진호','월하','연지'])
data_arr=np.random.randn(8,4)

print(name_arr)
print(data_arr)

['지빈' '명환' '연지' '하람' '연지' '진호' '월하' '연지']
[[ 0.75229036 -0.26157674 -0.7814826  -0.45571869]
 [ 0.67749077  0.96345637 -0.20702737 -0.69558193]
 [-0.96969908  1.20454212 -1.84246183 -0.49357026]
 [-0.48283978 -0.40299504 -0.22471646  0.22464804]
 [-1.75014949 -1.07556926 -1.2953752   0.87099096]
 [-0.02656501 -0.40507887  1.15102918  0.22599836]
 [-1.77609659 -2.6726835  -0.72991243  0.72313416]
 [ 1.28646811 -0.78850375  1.07971214  0.74627977]]


In [ ]:
print(name_arr=='연지')

[False False  True False  True False False  True]


In [ ]:
print(data_arr[name_arr=='연지']) # 연지인 행 출력

[[-0.96969908  1.20454212 -1.84246183 -0.49357026]
 [-1.75014949 -1.07556926 -1.2953752   0.87099096]
 [ 1.28646811 -0.78850375  1.07971214  0.74627977]]


In [ ]:
print(data_arr[name_arr=='연지',2:]) # 연지인 행의 2열부터 출력
print(data_arr[name_arr=='연지',3])
print(data_arr[name_arr=='연지',3:4])

[[-1.84246183 -0.49357026]
 [-1.2953752   0.87099096]
 [ 1.07971214  0.74627977]]
[-0.49357026  0.87099096  0.74627977]
[[-0.49357026]
 [ 0.87099096]
 [ 0.74627977]]


In [ ]:
or_opp=(name_arr=='지빈')|(name_arr=='월하')
print(or_opp)
print(data_arr[or_opp])

[ True False False False False False  True False]
[[ 0.75229036 -0.26157674 -0.7814826  -0.45571869]
 [-1.77609659 -2.6726835  -0.72991243  0.72313416]]


In [ ]:
not_opp=~(name_arr=='하람')
print(not_opp)
print(data_arr[not_opp])

[ True  True  True False  True  True  True  True]
[[ 0.75229036 -0.26157674 -0.7814826  -0.45571869]
 [ 0.67749077  0.96345637 -0.20702737 -0.69558193]
 [-0.96969908  1.20454212 -1.84246183 -0.49357026]
 [-1.75014949 -1.07556926 -1.2953752   0.87099096]
 [-0.02656501 -0.40507887  1.15102918  0.22599836]
 [-1.77609659 -2.6726835  -0.72991243  0.72313416]
 [ 1.28646811 -0.78850375  1.07971214  0.74627977]]


In [ ]:
data_arr[name_arr=='명환']=7
print(data_arr)

[[ 0.75229036 -0.26157674 -0.7814826  -0.45571869]
 [ 7.          7.          7.          7.        ]
 [-0.96969908  1.20454212 -1.84246183 -0.49357026]
 [-0.48283978 -0.40299504 -0.22471646  0.22464804]
 [-1.75014949 -1.07556926 -1.2953752   0.87099096]
 [-0.02656501 -0.40507887  1.15102918  0.22599836]
 [-1.77609659 -2.6726835  -0.72991243  0.72313416]
 [ 1.28646811 -0.78850375  1.07971214  0.74627977]]


In [ ]:
data_arr[data_arr<0]=0
print(data_arr)

[[0.75229036 0.         0.         0.        ]
 [7.         7.         7.         7.        ]
 [0.         1.20454212 0.         0.        ]
 [0.         0.         0.         0.22464804]
 [0.         0.         0.         0.87099096]
 [0.         0.         1.15102918 0.22599836]
 [0.         0.         0.         0.72313416]
 [1.28646811 0.         1.07971214 0.74627977]]


In [ ]:
arange_data=np.arange(15).reshape((3,5))
print(arange_data)
print(arange_data.T)
print(np.transpose(arange_data))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
rand_data=np.random.randn(10)
print(rand_data)

[ 0.3000644  -0.56063202  0.47705357 -0.01482756 -1.44212077  1.04479472
  1.04186652 -0.29851434  1.45892479  0.65975401]


In [ ]:
result=[True if i>0 else False for i in rand_data] # if문이 참이면 True, 거짓이면 False
print(result)
print(type(result))

[True, False, True, False, False, True, True, False, True, True]
<class 'list'>


In [ ]:
result=np.where(rand_data>0,True,False)
print(result)
print(type(result),result.dtype)

[ True False  True False False  True  True False  True  True]
<class 'numpy.ndarray'> bool


In [ ]:
result=np.where(rand_data>0,True,rand_data)
print(result)
print(type(result),result.dtype)

[ 1.         -0.56063202  1.         -0.01482756 -1.44212077  1.
  1.         -0.29851434  1.          1.        ]
<class 'numpy.ndarray'> float64


In [ ]:
rand_data=np.random.normal(0,1,1000)
print(rand_data)
print(np.sum(rand_data))
print(np.std(rand_data))
print(np.var(rand_data))

[ 4.10078761e-02 -9.96797035e-01 -6.75764130e-01 -8.94933781e-02
 -1.37998944e+00  4.97166282e-01  3.94563168e-01  4.18678300e-01
 -2.98785159e-01 -5.30281382e-01 -4.40547618e-01  1.08685391e+00
  1.32676740e+00  7.89958777e-01 -1.14357996e-01 -4.44704494e-01
  6.99114355e-01 -1.11182947e+00 -9.65776635e-01  3.88301606e-01
 -1.07464006e-01 -8.14175936e-01  1.96682480e-01 -1.12917523e+00
  9.09535289e-01 -5.32092667e-01 -4.09606372e-01 -1.26814656e-01
  1.91816252e+00 -1.90967001e+00  4.71757030e-01 -7.64192770e-01
  1.69260368e-01  2.28233643e-01  1.60806384e-01  2.71247394e-01
  1.33122401e+00  6.72816605e-01 -8.40507123e-01 -3.78559956e-01
 -1.05272844e+00 -9.19761579e-01  9.98696712e-01 -1.56106423e+00
  3.89016638e-01  3.92320027e-01 -1.12314298e+00  7.98655828e-01
 -2.73662516e-02 -1.13829375e+00  1.72283056e-01 -6.23183460e-01
  1.46726118e+00 -7.83272626e-01 -2.47543246e-01 -1.07634709e+00
  1.24486144e+00 -8.25974375e-01 -1.16678264e+00  1.30297646e+00
  1.17905694e+00  7.03936

In [ ]:
rand_data=np.random.randn(2,5)
print(rand_data)
print(np.sum(rand_data))
print(np.sum(rand_data,0))
print(np.sum(rand_data,1))

print(rand_data.mean())
print(rand_data.mean(0))
print(rand_data.mean(1))

[[ 0.31130546 -1.57785394 -0.84023428 -0.49422392  0.14503907]
 [ 0.27178226  1.39522887  2.07473395 -0.06777551  0.60822239]]
1.8262243463251844
[ 0.58308772 -0.18262507  1.23449967 -0.56199943  0.75326146]
[-2.45596763  4.28219197]
0.18262243463251843
[ 0.29154386 -0.09131254  0.61724983 -0.28099971  0.37663073]
[-0.49119353  0.85643839]


In [ ]:
rand_data=np.random.normal(0,1,10)
print(rand_data)
print(np.sort(rand_data))


[ 0.43030701 -1.86171309  0.20982491  0.6905061  -1.44061797 -0.53505396
 -0.76861422  0.45942456  0.55656039 -0.30287139]
[-1.86171309 -1.44061797 -0.76861422 -0.53505396 -0.30287139  0.20982491
  0.43030701  0.45942456  0.55656039  0.6905061 ]


In [ ]:
rand_data=np.random.randn(3,5)
print(rand_data)
print(np.sort(rand_data))
print(np.sort(rand_data,-1))
print(np.sort(rand_data,None))

[[-0.32013265 -3.88539096 -1.50336644  0.18821631 -0.04250198]
 [ 1.38641998 -2.36255006 -0.29362619  0.52806034 -0.17248482]
 [ 0.12020512  0.85360505 -1.65433239  1.99979381 -1.24043983]]
[[-3.88539096 -1.50336644 -0.32013265 -0.04250198  0.18821631]
 [-2.36255006 -0.29362619 -0.17248482  0.52806034  1.38641998]
 [-1.65433239 -1.24043983  0.12020512  0.85360505  1.99979381]]
[[-3.88539096 -1.50336644 -0.32013265 -0.04250198  0.18821631]
 [-2.36255006 -0.29362619 -0.17248482  0.52806034  1.38641998]
 [-1.65433239 -1.24043983  0.12020512  0.85360505  1.99979381]]
[-3.88539096 -2.36255006 -1.65433239 -1.50336644 -1.24043983 -0.32013265
 -0.29362619 -0.17248482 -0.04250198  0.12020512  0.18821631  0.52806034
  0.85360505  1.38641998  1.99979381]


In [ ]:
print(np.sort(rand_data)) # 원본에 반영 안됨
print(rand_data)
print(rand_data.sort()) # 원본에 반영됨
print(rand_data)

[[-3.88539096 -1.50336644 -0.32013265 -0.04250198  0.18821631]
 [-2.36255006 -0.29362619 -0.17248482  0.52806034  1.38641998]
 [-1.65433239 -1.24043983  0.12020512  0.85360505  1.99979381]]
[[-0.32013265 -3.88539096 -1.50336644  0.18821631 -0.04250198]
 [ 1.38641998 -2.36255006 -0.29362619  0.52806034 -0.17248482]
 [ 0.12020512  0.85360505 -1.65433239  1.99979381 -1.24043983]]
None
[[-3.88539096 -1.50336644 -0.32013265 -0.04250198  0.18821631]
 [-2.36255006 -0.29362619 -0.17248482  0.52806034  1.38641998]
 [-1.65433239 -1.24043983  0.12020512  0.85360505  1.99979381]]


In [ ]:
print(np.argsort([8,2,9,4,2,5,2,1])) # 오름차순 순서를 알려줌

[7 1 4 6 3 5 0 2]


In [ ]:
rand_data=np.random.randint(2,9,20)
print(rand_data)

print(np.unique(rand_data))

print(np.unique(rand_data,return_counts=True)) # return_counts가 True이면 해당 고유값이 몇 번 발생했는지 반환됨

[3 5 5 7 7 5 6 6 4 4 6 2 5 2 8 6 6 3 3 7]
[2 3 4 5 6 7 8]
(array([2, 3, 4, 5, 6, 7, 8]), array([2, 3, 2, 4, 5, 3, 1]))


In [ ]:
rand_data=np.random.randint(2,9,5)
print(rand_data)
print(np.in1d(rand_data,[2,3])) # rand_data에 [2,3]이 있는지에 대한 T/F 반환

[3 5 3 3 2]
[ True False  True  True  True]


In [ ]:
rand_data=np.random.randint(2,9,(2,5))
print(rand_data)

print(np.intersect1d(rand_data[0],rand_data[1]))
print(np.union1d(rand_data[0],rand_data[1]))
print(np.setdiff1d(rand_data[0],rand_data[1]))
print(np.setdiff1d(rand_data[1],rand_data[0]))

[[3 3 3 5 3]
 [8 6 6 6 7]]
[]
[3 5 6 7 8]
[3 5]
[6 7 8]


In [ ]:
arange_data=np.arange(1,10)
print(arange_data)

[1 2 3 4 5 6 7 8 9]


In [ ]:
result=np.where(arange_data>0,True,False).sum()
print(result)

9
